### ISSUE TITLE
Truncated Messages at the end of the screen

### ISSUE THREAD

**Issue by KaiBusu** [dimelo/Dimelo-iOS#48]
Hello,

Device: iPhone SE (2nd Gen)
iOS: 16.0
SDK: Dimelo-iOS v2.6.1 and 2.6.2

![image](https://github.com/ringcentral/engage-digital-messaging-ios/assets/146738295/6e5500c2-46b4-46d5-8e8e-0aeb9b113d2a)

We appreciate any assistance with regard to this matter.

Thanks

**Comment by waelba** [comment]
hi @KaiBusu,

We have a ticket on our side and we will work on it soon.

Regards,

**Comment by nokiaowner** [comment]
Hi @waelba any news on this please?

Thank you

**Comment by waelba** [comment]
Hi @nokiaowner, 

This issue has been solved in the last release (v2.6.4). Can you check it in your side please? Thanks.

Regards,

**Comment by nokiaowner** [comment]
Hello, 

I tested using Dimelo (iOS) v2.6.4 and I confirmed the problem is still there.

**Comment by waelba** [comment]
Hi @nokiaowner,

Can you share your Dimelo integration code?

Regards,

**Comment by nokiaowner** [comment]
Let me know if this is enough. This is just part of the actual DimeloManager class we use:

`func createInAppMessagingView(orderId: String? = nil, productType: String? = nil) -> UIViewController? {
        if !isInitialized { initialize() }
        guard let dimelo = Dimelo.sharedInstance(), isInitialized else {
            return nil
        }
        
        configureMessagingViewStyle()
        
        addMetaInfo(dimelo: dimelo, orderId: orderId, productType: productType, resetOrderIdIfNil: true)
        return dimelo.chatViewController()
    }

func configureMessagingViewStyle() {
        
        guard let dimelo = Dimelo.sharedInstance() else {
            return
        }
        
        let neutral200 = XColor.Base.Neutral.v200
        let primary600 = XColor.Base.Primary.v600
        let information600 = XColor.Base.Information.v600
         
        dimelo.messageFont = XFont.regular.font(ofSize: .L)
        dimelo.userMessageBackgroundColor = primary600
        dimelo.agentMessageBackgroundColor = neutral200
        dimelo.createNewThreadBackgroundColor = neutral200
        
        dimelo.quickRepliesTextColor = information600
        dimelo.quickRepliesBorderColor = information600
        dimelo.quickRepliesBorderWidth = 2
        
        dimelo.systemMessageBackgroundColor = neutral200
        dimelo.systemMessageFont = XFont.regular.font(ofSize: .L)
        
        dimelo.sendTintColor = primary600
        dimelo.disabledSendButtonColor = neutral200
        
        dimelo.loadMoreMessagesButtonTextColor = primary600
        
        dimelo.tintColor = primary600
        dimelo.navigationBarTitleFont = XFont.semibold.font(ofSize: .L)
        dimelo.messageFieldFont = XFont.regular.font(ofSize: .M)
        dimelo.cursorTintColor = primary600
        
        dimelo.title = Assistance.TranslationKey.chatPageTitle.translation
    }

`

**Comment by nokiaowner** [comment]
`func createInAppMessagingView(orderId: String? = nil, productType: String? = nil) -> UIViewController? {
        if !isInitialized { initialize() }
        guard let dimelo = Dimelo.sharedInstance(), isInitialized else {
            return nil
        }
        
        configureMessagingViewStyle()
        
        addMetaInfo(dimelo: dimelo, orderId: orderId, productType: productType, resetOrderIdIfNil: true)
        return dimelo.chatViewController()
    }`

**Comment by nokiaowner** [comment]
This is part of our DimeloManager class implementation. Let me know if this is enough.

```
 func createInAppMessagingView(orderId: String? = nil, productType: String? = nil) -> UIViewController? {
        if !isInitialized { initialize() }
        guard let dimelo = Dimelo.sharedInstance(), isInitialized else {
            return nil
        }
        
        configureMessagingViewStyle()
        
        addMetaInfo(dimelo: dimelo, orderId: orderId, productType: productType, resetOrderIdIfNil: true)
        return dimelo.chatViewController()
    }

func configureMessagingViewStyle() {
   
        guard let dimelo = Dimelo.sharedInstance() else {
            return
        }
        
        let neutral200 = XColor.Base.Neutral.v200
        let primary600 = XColor.Base.Primary.v600
        let information600 = XColor.Base.Information.v600
         
        dimelo.messageFont = XFont.regular.font(ofSize: .L)
        dimelo.userMessageBackgroundColor = primary600
        dimelo.agentMessageBackgroundColor = neutral200
        dimelo.createNewThreadBackgroundColor = neutral200
        
        dimelo.quickRepliesTextColor = information600
        dimelo.quickRepliesBorderColor = information600
        dimelo.quickRepliesBorderWidth = 2
        
        dimelo.systemMessageBackgroundColor = neutral200
        dimelo.systemMessageFont = XFont.regular.font(ofSize: .L)
        
        dimelo.sendTintColor = primary600
        dimelo.disabledSendButtonColor = neutral200
        
        dimelo.loadMoreMessagesButtonTextColor = primary600
        
        dimelo.tintColor = primary600
        dimelo.navigationBarTitleFont = XFont.semibold.font(ofSize: .L)
        dimelo.messageFieldFont = XFont.regular.font(ofSize: .M)
        dimelo.cursorTintColor = primary600
        
        dimelo.title = Assistance.TranslationKey.chatPageTitle.translation
    }

```

**Comment by waelba** [comment]
Hi @nokiaowner,

Thanks for your response. Can you also share the code snippet of dimelo chat integration in your view pager ?

Regards,
